import { Activity } from "@/types/data";
import { contacts } from "./contacts";

// Dummy activity data
export const activities: Activity[] = [
  {
    id: "1",
    title: "Client Meeting - Quarterly Review",
    type: "meeting",
    status: "completed",
    priority: "high",
    dueDate: new Date("2023-12-15"),
    owner: contacts[0],
    duration: 60,
    description: "Quarterly performance review with client",
    completedAt: new Date("2023-12-15T14:30:00"),
    createdAt: new Date("2023-12-01T09:00:00"),
  },
  {
    id: "2",
    title: "Follow-up Email Campaign",
    type: "email",
    status: "in-progress",
    priority: "medium",
    dueDate: new Date("2023-12-18"),
    owner: contacts[2],
    duration: 120,
    description: "Send follow-up emails to potential leads",
    createdAt: new Date("2023-12-05T11:30:00"),
  },
  {
    id: "3",
    title: "Product Demo Preparation",
    type: "task",
    status: "not-started",
    priority: "high",
    dueDate: new Date("2023-12-20"),
    owner: contacts[4],
    duration: 180,
    description: "Prepare materials for product demo",
    createdAt: new Date("2023-12-10T14:00:00"),
  },
  {
    id: "4",
    title: "Team Strategy Session",
    type: "meeting",
    status: "completed",
    priority: "medium",
    dueDate: new Date("2023-12-12"),
    owner: contacts[1],
    duration: 90,
    description: "Quarterly planning session with team",
    completedAt: new Date("2023-12-12T16:00:00"),
    createdAt: new Date("2023-12-01T10:15:00"),
  },
  {
    id: "5",
    title: "Client Proposal Documentation",
    type: "task",
    status: "in-progress",
    priority: "high",
    dueDate: new Date("2023-12-22"),
    owner: contacts[2],
    duration: 240,
    description: "Draft proposal for new client engagement",
    createdAt: new Date("2023-12-08T13:45:00"),
  },
  {
    id: "6",
    title: "Networking Event",
    type: "event",
    status: "not-started",
    priority: "low",
    dueDate: new Date("2023-12-28"),
    owner: contacts[2],
    duration: 120,
    description: "Industry networking conference",
    createdAt: new Date("2023-12-15T09:30:00"),
  },
];
