import { Company } from "@/types/data";
import { contacts } from "./contacts";

export const companies: Company[] = [
  {
    id: "1",
    name: "TechCorp Solutions",
    email: "info@techcorp.com",
    phone: "+1 (555) 123-4567",
    tags: ["Collab", "VIP"],
    owner: contacts[0],
    status: "active",
    location: {
      city: "San Francisco",
      country: "United States",
      countryCode: "us",
    },
    avatar: "https://logo.clearbit.com/techcorp.com",
    website: "https://techcorp.com",
    industry: "Technology",
    employees: 250,
    revenue: "$50M",
    founded: 2010,
    role: "Technician",
    isPrivate: true,
    rating: "4.5",
  },
  {
    id: "2",
    name: "GreenEnergy Innovations",
    email: "contact@greenenergy.com",
    phone: "+1 (555) 987-6543",
    tags: ["Collab", "VIP"],
    owner: contacts[2],
    status: "inactive",
    location: {
      city: "Austin",
      country: "United States",
      countryCode: "us",
    },
    avatar: "https://logo.clearbit.com/greenenergy.com",
    website: "https://greenenergy.com",
    industry: "Energy",
    employees: 75,
    revenue: "$15M",
    founded: 2018,
    role: "Technician",
    isPrivate: false,
    rating: "4.5",
  },
  {
    id: "3",
    name: "Global Finance Partners",
    email: "support@gfpartners.com",
    phone: "+44 20 1234 5678",
    tags: ["Collab", "VIP"],
    owner: contacts[2],
    status: "active",
    location: {
      city: "London",
      country: "United Kingdom",
      countryCode: "gb",
    },
    avatar: "https://logo.clearbit.com/gfpartners.com",
    website: "https://gfpartners.com",
    industry: "Finance",
    employees: 500,
    revenue: "$200M",
    founded: 1995,
    role: "Technician",
    isPrivate: false,
    rating: "4.5",
  },
  {
    id: "4",
    name: "MediCare Systems",
    email: "hello@medicare.com",
    phone: "+1 (555) 456-7890",
    tags: ["Collab", "VIP"],
    owner: contacts[3],
    status: "active",
    location: {
      city: "Boston",
      country: "United States",
      countryCode: "us",
    },
    avatar: "https://logo.clearbit.com/medicare.com",
    website: "https://medicare.com",
    industry: "Healthcare",
    employees: 1200,
    revenue: "$500M",
    founded: 1985,
    role: "Technician",
    isPrivate: false,
    rating: "4.5",
  },
  {
    id: "5",
    name: "Urban Retail Group",
    email: "contact@urbanretail.com",
    phone: "+1 (555) 789-0123",
    tags: ["Collab", "VIP"],
    owner: contacts[1],
    status: "inactive",
    location: {
      city: "New York",
      country: "United States",
      countryCode: "us",
    },
    avatar: "https://logo.clearbit.com/urbanretail.com",
    website: "https://urbanretail.com",
    industry: "Retail",
    employees: 300,
    revenue: "$75M",
    founded: 2015,
    role: "Technician",
    isPrivate: false,
    rating: "4.5",
  },
  {
    id: "6",
    name: "Ocean Shipping Ltd",
    email: "info@oceanshipping.com",
    phone: "+65 6123 4567",
    tags: ["Collab", "VIP"],
    owner: contacts[2],
    status: "active",
    location: {
      city: "Singapore",
      country: "Singapore",
      countryCode: "sg",
    },
    avatar: "https://logo.clearbit.com/oceanshipping.com",
    website: "https://oceanshipping.com",
    industry: "Transportation",
    employees: 800,
    revenue: "$300M",
    founded: 2005,
    role: "Technician",
    isPrivate: false,
    rating: "4.5",
  },
  {
    id: "7",
    name: "Skyline Construction",
    email: "contact@skylinebuild.com",
    phone: "+1 (555) 234-5678",
    tags: ["Collab", "VIP"],
    owner: contacts[0],
    status: "active",
    location: {
      city: "Chicago",
      country: "United States",
      countryCode: "us",
    },
    avatar: "https://logo.clearbit.com/skylinebuild.com",
    website: "https://skylinebuild.com",
    industry: "Construction",
    employees: 150,
    revenue: "$40M",
    founded: 2012,
    role: "Technician",
    isPrivate: false,
    rating: "4.5",
  },
  {
    id: "8",
    name: "FoodFiesta Group",
    email: "support@foodfiesta.com",
    phone: "+1 (555) 345-6789",
    tags: ["Collab", "VIP"],
    owner: contacts[1],
    status: "active",
    location: {
      city: "Miami",
      country: "United States",
      countryCode: "us",
    },
    avatar: "https://logo.clearbit.com/foodfiesta.com",
    website: "https://foodfiesta.com",
    industry: "Food & Beverage",
    employees: 450,
    revenue: "$120M",
    founded: 2008,
    role: "Technician",
    isPrivate: false,
    rating: "4.5",
  },
];
