import { Lead } from "@/types/data";
import { companies } from "./companies";
import { contacts } from "./contacts";

export const initialLeads: Lead[] = [
  {
    id: "1",
    name: "Alex Johnson",
    email: "alex.johnson@techcorp.com",
    phone: "+1 (555) 123-4567",
    company: companies[0],
    title: "CTO",
    stage: "lost",
    source: "website",
    value: 50000,
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    priority: "high",
    location: {
      country: "Martin Lewis",
      countryCode: "co",
      city: "",
    },
    owner: contacts[0],
    ceatedAt: "2023-10-01T12:00:00Z",
    isPrivate: true,
    tags: ["Collab", "VIP"],
    projects: ["Devops Design", "Margrate Design"],
  },
  {
    id: "2",
    name: "Sarah Williams",
    email: "sarah.w@greenenergy.com",
    phone: "+1 (555) 987-6543",
    company: companies[1],
    title: "Purchasing Manager",
    stage: "contacted",
    source: "event",
    value: 35000,
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    priority: "medium",
    location: {
      country: "Martin Lewis",
      countryCode: "co",
      city: "",
    },
    owner: contacts[0],
    ceatedAt: "2023-10-01T12:00:00Z",
    isPrivate: false,
    tags: ["Collab", "VIP"],
    projects: ["Devops Design", "Margrate Design"],
  },
  {
    id: "3",
    name: "Michael Chen",
    email: "michael.c@globalfinance.com",
    phone: "+44 20 1234 5678",
    company: companies[1],
    title: "Director of Operations",
    stage: "closed",
    source: "referral",
    value: 75000,
    avatar: "https://randomuser.me/api/portraits/men/75.jpg",
    priority: "high",
    location: {
      country: "Martin Lewis",
      countryCode: "co",
      city: "",
    },
    owner: contacts[1],
    ceatedAt: "2023-10-01T12:00:00Z",
    isPrivate: false,
    tags: ["Collab", "VIP"],
    projects: ["Devops Design", "Margrate Design"],
  },
  {
    id: "4",
    name: "Emma Rodriguez",
    email: "emma.r@healthcare.org",
    phone: "+1 (555) 456-7890",
    company: companies[2],
    title: "IT Manager",
    stage: "notcontacted",
    source: "social",
    value: 60000,
    avatar: "https://randomuser.me/api/portraits/women/63.jpg",
    priority: "medium",
    location: {
      country: "Martin Lewis",
      countryCode: "co",
      city: "",
    },
    owner: contacts[2],
    ceatedAt: "2023-10-01T12:00:00Z",
    isPrivate: false,
    tags: ["Collab", "VIP"],
    projects: ["Devops Design", "Margrate Design"],
  },
  {
    id: "5",
    name: "David Kim",
    email: "david.k@retailgroup.com",
    phone: "+1 (555) 789-0123",
    company: companies[1],
    title: "VP of Technology",
    stage: "contacted",
    source: "website",
    value: 45000,
    avatar: "https://randomuser.me/api/portraits/men/81.jpg",
    priority: "low",
    location: {
      country: "Martin Lewis",
      countryCode: "co",
      city: "",
    },
    owner: contacts[4],
    ceatedAt: "2023-10-01T12:00:00Z",
    isPrivate: false,
    tags: ["Collab", "VIP"],
    projects: ["Devops Design", "Margrate Design"],
  },
  {
    id: "6",
    name: "Olivia Martinez",
    email: "olivia.m@logistics.com",
    phone: "+65 6123 4567",
    company: companies[4],
    title: "Operations Director",
    stage: "lost",
    source: "event",
    value: 30000,
    avatar: "https://randomuser.me/api/portraits/women/28.jpg",
    priority: "medium",
    location: {
      country: "Martin Lewis",
      countryCode: "co",
      city: "",
    },
    owner: contacts[3],
    ceatedAt: "2023-10-01T12:00:00Z",
    isPrivate: false,
    tags: ["Collab", "VIP"],
    projects: ["Devops Design", "Margrate Design"],
  },
  {
    id: "7",
    name: "James Wilson",
    email: "james.w@construction.com",
    phone: "+1 (555) 234-5678",
    company: companies[2],
    title: "CFO",
    stage: "closed",
    source: "referral",
    value: 55000,
    avatar: "https://randomuser.me/api/portraits/men/92.jpg",
    priority: "high",
    location: {
      country: "Martin Lewis",
      countryCode: "co",
      city: "",
    },
    owner: contacts[2],
    ceatedAt: "2023-10-01T12:00:00Z",
    isPrivate: false,
    tags: ["Collab", "VIP"],
    projects: ["Devops Design", "Margrate Design"],
  },
  {
    id: "8",
    name: "Sophia Lee",
    email: "sophia.l@foodindustry.com",
    phone: "+1 (555) 345-6789",
    company: companies[0],
    title: "Purchasing Director",
    stage: "notcontacted",
    source: "website",
    value: 40000,
    avatar: "https://randomuser.me/api/portraits/women/36.jpg",
    priority: "medium",
    location: {
      country: "Martin Lewis",
      countryCode: "co",
      city: "",
    },
    owner: contacts[0],
    isPrivate: false,
    tags: ["Collab", "VIP"],
    projects: ["Devops Design", "Margrate Design"],
  },
];

export const stageGroupsLeads = [
  {
    id: "contacted",
    title: "Contacted",
    count: initialLeads.filter((l) => l.stage === "contacted").length,
    color: "#10B981",
  },
  {
    id: "notcontacted",
    title: "Not contacted",
    count: initialLeads.filter((l) => l.stage === "notcontacted").length,
    color: "#6B7280",
  },
  {
    id: "closed",
    title: "Closed",
    count: initialLeads.filter((l) => l.stage === "closed").length,
    color: "#3B82F6",
  },
  {
    id: "lost",
    title: "Lost",
    count: initialLeads.filter((l) => l.stage === "lost").length,
    color: "#EF4444",
  },
];
