import { Project } from "@/types/data";
import { companies } from "./companies";
import { contacts } from "./contacts";

export const projects: Project[] = [
  {
    id: "1",
    name: "E-commerce Website Redesign",
    description: "Complete redesign of the company e-commerce platform",
    status: "active",
    priority: "high",
    startDate: "2023-05-15",
    endDate: "2023-09-30",
    progress: 65,
    team: ["Design Team", "Development Team"],
    category: "website",
    budget: 25000,
    avatar:
      "https://crms.dreamstechnologies.com/html/template/assets/img/priority/project-01.svg",
    users: [...contacts.slice(0, 7)],
    client: companies[3],
    hours: 3,
    pipelineStage: "conversation",
    isPrivate: true,
    value: "$25,11,145",
    teamLeader: contacts[0],
  },
  {
    id: "2",
    name: "Mobile Banking App",
    description: "Development of a new mobile banking application",
    status: "active",
    priority: "medium",
    startDate: "2023-06-01",
    endDate: "2023-11-15",
    progress: 30,
    team: ["Development Team"],
    category: "mobile",
    budget: 18000,
    avatar:
      "https://crms.dreamstechnologies.com/html/template/assets/img/priority/project-01.svg",
    users: [...contacts.slice(0, 4)],
    client: companies[1],
    hours: 2,
    pipelineStage: "win",
    isPrivate: false,
    value: "$25,11,145",
    teamLeader: contacts[2],
  },
  {
    id: "3",
    name: "Brand Identity Design",
    description: "Create new brand identity for startup company",
    status: "inactive",
    priority: "low",
    startDate: "2023-03-10",
    endDate: "2023-05-20",
    progress: 100,
    team: ["Design Team"],
    category: "branding",
    budget: 8000,
    avatar:
      "https://crms.dreamstechnologies.com/html/template/assets/img/priority/project-01.svg",
    users: [...contacts.slice(0, 4)],
    client: companies[2],
    hours: 5,
    pipelineStage: "lost",
    isPrivate: false,
    value: "$25,11,145",
    teamLeader: contacts[1],
  },
  {
    id: "4",
    name: "Marketing Campaign",
    description: "Summer product marketing campaign",
    status: "active",
    priority: "medium",
    startDate: "2023-07-01",
    endDate: "2023-08-31",
    progress: 45,
    team: ["Marketing Team"],
    category: "marketing",
    budget: 12000,
    avatar:
      "https://crms.dreamstechnologies.com/html/template/assets/img/priority/project-01.svg",
    users: [...contacts.slice(0, 4)],
    client: companies[1],
    hours: 13,
    pipelineStage: "inPipeline",
    isPrivate: false,
    value: "$25,11,145",
    teamLeader: contacts[3],
  },
  {
    id: "5",
    name: "Internal Dashboard",
    description: "Development of analytics dashboard for internal use",
    status: "inactive",
    priority: "high",
    startDate: "2023-04-15",
    endDate: "2023-06-30",
    progress: 85,
    team: ["Development Team"],
    category: "website",
    budget: 15000,
    avatar:
      "https://crms.dreamstechnologies.com/html/template/assets/img/priority/project-01.svg",
    users: [...contacts.slice(0, 4)],
    client: companies[3],
    hours: 4,
    pipelineStage: "win",
    isPrivate: false,
    value: "$25,11,145",
    teamLeader: contacts[4],
  },
];
